var precipitationTexts = {
    drizzle: 'Drizzle reduces visibility to three-quarters of the normal range, imposing a –2 penalty on Perception checks. It automatically extinguishes tiny unprotected flames (candles and the like, but not torches).',
    allFog: '<b>Fog:</b> Fog typically occurs early in the day, late in the day, or sometimes at night, but the heat of the midday usually burns it away. Fog occurs only when there is no or light wind.',
    lightFog: 'Light fog reduces visibility to three-quarters of the normal ranges, resulting in a –2 penalty on Perception checks and a –2 penalty on ranged attacks.',
    mediumFog: 'Medium fog reduces visibility ranges by half, resulting in a –4 penalty on Perception checks and a –4 penalty on ranged attacks.',
    heavyFog: 'Heavy fog obscures all vision beyond 5 feet, including darkvision. Creatures 5 feet away have concealment.',
    rain: 'Rain reduces visibility ranges by half, resulting in a –4 penalty on Perception checks. Rain automatically extinguishes unprotected flames (candles, torches, and the like) and imposes a –4 penalty on ranged attacks.',
    heavyRain: 'Heavy rain reduces visibility to one-quarter of the normal range, resulting in a –6 penalty on Perception checks. Heavy rain automatically extinguishes unprotected flames and imposes a –6 penalty on ranged attacks.',
    sleet: 'Essentially frozen rain, sleet has the same effect as light snow, but any accumulation typically doesn’t last longer than 1–2 hours after the storm.',
    lightSnow: 'Light snow reduces visibility to three-quarters of the normal range, resulting in a –2 penalty on Perception checks. Light snow has a 75% chance each hour of extinguishing unprotected flames and imposes a –2 penalty on ranged attacks. Light snow does not impede movement unless it continues for 2 or more hours, at which point moving into a square of such snow requires 1 extra 5-foot square of movement (this stacks with difficult terrain). Every 2 hours of light snow leaves 1 inch of snow on the ground. As long as at least 2 inches of snow remain on the ground, the requirement of an extra square of movement to enter a square of snow persists. If at least 1 foot of snow remains on the ground, entering a snow-filled square instead requires 2 extra squares of movement.',
    mediumSnow: 'Medium snow reduces visibility ranges by half, resulting in a –4 penalty on Perception checks. Medium snow extinguishes unprotected flames and imposes a –4 penalty on ranged attacks. Medium snow does not impede movement unless it continues for 1 hour, at which point moving into a square of such snow requires 1 extra 5-foot square of movement (this stacks with difficult terrain). Every hour of medium snow leaves 1 inch of snow on the ground. As long as at least 2 inches of snow remain on the ground, the requirement of an extra square of movement to enter a square of snow persists. If at least 1 foot of snow remains on the ground, entering a snow-filled square instead requires 2 extra squares of movement.',
    heavySnow: 'Heavy snow reduces visibility ranges to one-quarter of the normal range, resulting in a –6 penalty on Perception checks. It extinguishes unprotected flames and imposes a –6 penalty on ranged attacks. Heavy snow impedes movement even before it begins to stick. Moving into a square during a heavy snowstorm requires 1 extra 5-foot square of movement (this stacks with difficult terrain). Every hour of heavy snow leaves 1d4 inches of snow on the ground. As long as at least 2 inches of snow remain on the ground, the requirement of an extra square of movement to enter a square of snow persists. If at least 1 foot of snow remains on the ground, 2 extra squares of movement are required to enter a snow-filled square instead. A heavy snowstorm has a 10% chance of generating thundersnow and has a 40% chance of becoming a blizzard if the wind speed is severe or stronger.',
    thunderstorm: 'Thunderstorms feature powerful winds and heavy rain. See other precipitation effects.',
    lightning: 'Every 10 minutes during a thunderstorm, a bolt of lightning strikes an unsheltered creature at random (though this can strike wildlife as easily as PCs). A creature struck by this lightning must succeed a DC 18 Reflex saving throw or take 10d8 points of electricity damage (a successful saving throw halves the damage). Creatures in metal armor take a –4 penalty on the Reflex saving throw.',
    blizzard: 'A combination of severe or stronger winds with heavy snow can create blizzard conditions. Blizzards reduce range of vision to no more than 20 feet, and even then, creatures takes a –8 penalty on Perception checks within that range. In a blizzard, the snowfall increases to 4 inches of snow each hour, and travel in more than 3 feet of snow is usually impossible without snowshoes or an ability such as waterwalk. Furthermore, the high winds make it feel (and affect living creatures) as if the temperature were 20° F colder. There is a 20% chance that a blizzard lasts for 2d12 hours instead of the normal duration for heavy snow.',
    hail: 'Hail typically occurs just before or during a thunderstorm. Hail does not reduce visibility, but the sound of falling hail imposes a –4 penalty on sound-based Perception checks. Rarely (5% chance), hail pellets can become large enough to deal 1d4 points of lethal damage per minute to creatures and objects out in the open.',
    hurricane: 'Hurricanes are incredibly massive storms featuring heavy rain and a wind strength greater than that of the most powerful windstorm. With winds of 75–174 miles per hour, a hurricane renders ranged attacks impossible, and siege weapons take a –8 penalty on attack rolls. Large or smaller creatures must succeed at a DC 15 Strength check or they are unable to move forward against the strength of the wind. Medium or smaller creatures on the ground must succeed at a DC 15 Strength check or they are knocked prone and roll 1d6x10 feet, taking 1d6 points of nonlethal damage per 10 feet. Flying creatures must succeed at a DC 25 Fly check or they are blown back 2d8×10 feet and take 4d6 points of nonlethal damage due to battering and buffeting. Hurricanes also usually cause flooding. It’s nearly impossible to journey out into a hurricane unscathed.',
    sandstorm: 'Sandstorms occur when severe or greater winds kick up sand and debris in a desert or similarly arid environment. Sandstorms reduce visibility to 1d10×10 feet, and those within them take a –6 penalty on Perception checks. Sandstorms deal 1d3 points of nonlethal damage per hour to creatures caught in the open.',
    thundersnow: 'High winds in a snowstorm can create the rare phenomena known as thundersnow. Lighting strikes are less common in thundersnow, but just as deadly. Every hour during the storm, a bolt of lightning strikes an unsheltered creature at random (though this can strike wildlife as easily as PCs). A creature struck by this lightning must succeed a DC 18 Reflex saving throw or take 10d8 points of electricity damage (a successful saving throw halves the damage). Creatures in metal armor take a –4 penalty on the Reflex saving throw.',
    tornado: 'With winds with speeds of 174–300 miles per hour, tornados are deadly terrors. The smallest tornados occupy a 20-foot-radius burst, with winds of windstorm strength swirling up to 100 feet beyond that burst. The largest tornados can be 100-foot-radius bursts, with a windstorm whose radius extends 500 feet beyond that burst. Ranged attacks, including normal, siege, and even those produced by evocation spells, are impossible in the core burst of a tornado. Huge or smaller creatures must succeed a DC 20 Strength check or be sucked up by the funnel of the tornado; this deals 8d8 points of bludgeoning, piercing, and slashing lethal damage to the creatures. This damage ignores all but DR/epic, DR/—, and hardness. Once it deals this damage, the tornado flings the creature it has sucked up 1d20×10 feet up and away from the tornado, dealing 1d6 points of falling damage per 10 feet that the creature is flung. Gargantuan and larger creatures take the 8d8 points of damage but are not moved by the tornado. A tornado moves at a speed of 40 feet, though the direction it moves is entirely unpredictable—you can determine the direction randomly each round. Tornados typically last for 3d6 minutes, but some can swirl for up to an hour. While most tornados are created by thunderstorms, some smaller tornados (typically with a 5- to 10-foot-burst radius, with no outer radius) can be created in areas of wildfire (firenados), snow (snownados), or sand (dust devils). They deal a similar amount of damage, but firenados deal fire damage, snownados deal cold damage, and dust devils deal bludgeoning damage only, and these types of tornados do not fling their targets.',
    wildfire: 'While wildfires can be sparked a number of ways, for these rules, they are usually created by a lightning strike in a particularly dry area of forest or other vegetation. Use the rules for forest fires, but add a 10% chance of the fire producing 1d6 firenados (see Tornado above).'
};

var hotTemperatureTexts = {
    all: '<b>Heat:</b> Heat deals nonlethal damage that cannot be recovered from until the character gets cooled off (reaches shade, survives until nightfall, gets doused in water, is targeted by endure elements, and so forth). Once a character has taken an amount of nonlethal damage equal to her total hit points, any further damage from a hot environment is lethal damage. Characters wearing heavy clothing or any sort of armor take a –4 penalty on their saves. A character with the Survival skill may receive a bonus on this saving throw and might be able to apply this bonus to other characters as well (see the skill description).',
    veryHot: 'A character in very hot conditions (above 90° F) must make a Fortitude saving throw each hour (DC 15, +1 for each previous check) or take 1d4 points of nonlethal damage. Characters reduced to unconsciousness begin taking lethal damage (1d4 points per hour).',
    severeHeat: 'In severe heat (above 110° F), a character must make a Fortitude save once every 10 minutes (DC 15, +1 for each previous check) or take 1d4 points of nonlethal damage. Characters reduced to unconsciousness begin taking lethal damage (1d4 points per each 10-minute period). A character who takes any nonlethal damage from heat exposure now suffers from heatstroke and is fatigued. These penalties end when the character recovers from the nonlethal damage she took from the heat.',
    extremeHeat: 'Extreme heat (air temperature over 140° F, fire, boiling water, lava) deals lethal damage. Breathing air in these temperatures deals 1d6 points of fire damage per minute (no save). In addition, a character must make a Fortitude save every 5 minutes (DC 15, +1 per previous check) or take 1d4 points of nonlethal damage.'
};

var coldTemperatureTexts = {
    all: '<b>Cold:</b> Cold and exposure deal nonlethal damage to the victim. A character cannot recover from the damage dealt by a cold environment until she gets out of the cold and warms up again. Once a character has taken an amount of nonlethal damage equal to her total hit points, any further damage from a cold environment is lethal damage. A character who has the Survival skill may receive a bonus on this saving throw and might be able to apply this bonus to other characters as well (see the skill description).',
    veryCold: 'An unprotected character in cold weather (below 40° F) must make a Fortitude save each hour (DC 15, +1 per previous check) or take 1d6 points of nonlethal damage.',
    severeCold: 'In conditions of severe cold or exposure (below 0° F), an unprotected character must make a Fortitude save once every 10 minutes (DC 15, +1 per previous check), taking 1d6 points of nonlethal damage on each failed save. Characters wearing a cold weather outfit only need check once per hour for cold and exposure damage. A character who takes any nonlethal damage from cold or exposure is beset by frostbite or hypothermia (treat her as fatigued). These penalties end when the character recovers the nonlethal damage she took from the cold and exposure.',
    extremeCold: 'Extreme cold (below –20° F) deals 1d6 points of lethal damage per minute (no save). In addition, a character must make a Fortitude save (DC 15, +1 per previous check) or take 1d4 points of nonlethal damage.'
};

var altitudeTexts = {
    highland: '<b>Low Peak or High Pass (5,000 to 15,000 feet):</b> All non-acclimated creatures labor to breathe in the thin air at this altitude. Characters must succeed on a Fortitude save each hour (DC 15, +1 per previous check) or be fatigued. The fatigue ends when the character descends to an altitude with more air. Acclimated characters do not have to attempt the Fortitude save.',
    highpeak: '<b>High Peak (more than 15,000 feet):</b> The highest mountains exceed 15,000 feet in height. At these elevations, creatures are subject to both high altitude fatigue (Characters must succeed on a Fortitude save each hour (DC 15, +1 per previous check) or be fatigued.) and altitude sickness, whether or not they’re acclimated to high altitudes. Altitude sickness represents long-term oxygen deprivation, and affects mental and physical ability scores. After each 6-hour period a character spends at an altitude of over 15,000 feet, he must succeed on a Fortitude save (DC 15, +1 per previous check) or take 1 point of damage to all ability scores. Creatures acclimated to high altitude receive a +4 competence bonus on their saving throws to resist high altitude effects and altitude sickness, but eventually even seasoned mountaineers must abandon these dangerous elevations.'
};

var windDirection = ['n', 'nne', 'ne', 'ene', 'e', 'ese', 'se', 'sse', 's', 'ssw', 'sw', 'wsw', 'w', 'wnw', 'nw', 'nnw'];






